// require('./bank/_route')
// require('./client/_route')
// require('./upload/_route')
// require('./_router_user')
// require('./_router_menu')
// require('./_router_permission')
// require('./_router_role')
require('./_router_test')
